postgres:
  image: postgres:11-alpine
  container_name: postgres
  environment:
    - "TZ=Europe/Amsterdam"
    - "POSTGRES_USER=docker"
    - "POSTGRES_PASSWORD=docker"
  ports:
    - "5432:5432"  # credentials (docker:docker)
  volumes:
    - "./initdb:/docker-entrypoint-initdb.d"
